# Generated by Django 4.0.6 on 2022-07-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Starting date')),
                ('date_end', models.DateTimeField(verbose_name='Ending date')),
                ('duration', models.DurationField()),
            ],
        ),
    ]
