# Generated by Django 4.0.6 on 2022-07-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_marbar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='marbar',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='marbar',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ending date'),
        ),
        migrations.AlterField(
            model_name='marbar',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Starting date'),
        ),
    ]
