# Generated by Django 4.0.6 on 2022-07-14 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_marbar_note_alter_marbar_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marbar',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=3)),
        ),
    ]
