# Generated by Django 4.0.6 on 2022-07-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_marbar_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marbar',
            name='date_end',
        ),
        migrations.AlterField(
            model_name='marbar',
            name='date_start',
            field=models.DateTimeField(verbose_name='Starting date'),
        ),
    ]
